### ISSUE TITLE
Optional error loggin on a file

### ISSUE THREAD

**Issue by sebassdc** [jneidel/mangareader-dl#1]
It could be an option to log the error on a file an just an "Error" word in red on the side of the downloading bar

**Comment by jneidel** [comment]
Showing an error in the progress bar is a good idea.

I'm already sending errors to my api, which I prefer over saving them locally.

My error handler ([jneidel/err-hndlr](https://github.com/jneidel/err-hndlr)) is not complete yet, so I will continue to optimize the error handling for this module as well.
