### ISSUE TITLE
Pages in wrong order

### ISSUE THREAD

**Issue by kakaroto** [jneidel/mangareader-dl#3]
Trying to download a manga and the pages are in the wrong order. I got confused for a bit until I compared with mangareader content and other versions of the manga I had (pdf) and finally figured out they were all in the wrong order (viewed on ComicRack v0.9.1.156).
I went with a clean config and used `mangareader-dl shingeki-no-kyojin` and all the cbz have their pages out of order, the first page is correct, but page 2 appears at page 12 in ComicRack, page 3 is in page 23, page 4 is in page 34, etc... 
I unzipped the cbz and found the page numbers correct in the filenames, but the format `<name>-<chapter>-<page>.jpg` without leading zeroes in the page numbers causes ComicRack to put the pages in the wrong order since it sorts by filename and "shingeki-no-kyojin-1-2.jpg" comes after "shingeki-no-kyojin-1-19.jpg"
I've never done any JS before, but a grep for 'jpg' leads to one result, and a quick google search for how to add leading zeroes to a string in javascript gave me a simple answer, which I've tested and can confirm it works. I'm not going to bother sending a pull request since I'm sure you can do it better/cleaner, also, this assumes a maximum of 999 pages per comic, but this is the solution I've used and which works for me :
```
diff --git a/lib/index.js b/lib/index.js
index 62caee5..5dd1046 100644
--- a/lib/index.js
+++ b/lib/index.js
@@ -172,7 +172,9 @@ async function createZip( buffers, name, chapter, outputPath ) {
 
   let i = 1;
   for ( const buffer of buffers ) {
-    await zip.file( `${name}-${chapter}-${i}.jpg`, buffer.buff, { binary: true } );
+    var i0 = "000" + i;
+    i0 = i0.substr(i0.length-3);
+    await zip.file( `${name}-${chapter}-${i0}.jpg`, buffer.buff, { binary: true } );
     i++;
   }

```

btw, any idea why this was never noticed before? I'd assume ComicRack is popular enough that this issue would have been brought up before...

**Comment by jneidel** [comment]
Thanks for taking the time to bring this up!

I personally use YACReader, which does not have a problem with this.

Pages are now saved with leading zeros: `naruto-004-002.jpg`.
See [commit changes](https://github.com/jneidel/mangareader-dl/commit/270730347ebb34b169b428a2029f7e0ed42caee1).

**Comment by kakaroto** [comment]
Great, thanks for handling! :)
And as expected, you did it with a much cleaner method :)

**Comment by jneidel** [comment]
Yeah, I just used an existing utility ([leftpad](https://www.npmjs.com/package/left-pad)) :)

I just updated the npm package, so you can install the latest version with:
```shell
npm i -g mangareader-dl@0.3.2
```
